### PR TITLE
Add ApproximatePeriodicKernel

### PR DESCRIPTION
**Pull request by theogf**
This is an attempt at #61

Left todo:
- [x] Add tests for the `ApproxPeriodicKernel`

### CODE REVIEW

**Comment by theogf** [comment]
Will be splitted to treat the `Sum` first.

**Comment by theogf** [comment]
Another issue is with the argument for the PeriodicKernel, it is bounded but we do not do any transformation. This is messing up computations when using `FiniteDifferences`

**Review by simsurace — APPROVED** [review]
Looks clean. Maybe a few tests comparing a normal GP to a temporal GP with `ApproxPeriodixKernel` would add some safety, e.g. comparing the `logpdf` output and maybe posterior mean and variance.

**Comment by theogf** [comment]
> Looks clean. Maybe a few tests comparing a normal GP to a temporal GP with `ApproxPeriodixKernel` would add some safety, e.g. comparing the `logpdf` output and maybe posterior mean and variance.

This is already the case! If you look at the lti_sde tests, the prior is compared against a "naive" GP.

**Comment by simsurace** [comment]
> > Looks clean. Maybe a few tests comparing a normal GP to a temporal GP with `ApproxPeriodixKernel` would add some safety, e.g. comparing the `logpdf` output and maybe posterior mean and variance.
> 
> This is already the case! If you look at the lti_sde tests, the prior is compared against a "naive" GP.

Inded, thanks!

**Comment by theogf** [comment]
@willtebbutt this is fully ready for a review.

**Comment by simsurace** [comment]
@willtebbutt are there any blockers for this?

**Pull request merged**
